// AUTO-GENERATED from apps/systems-web/src/lib/{services,nav}.ts — the marketing site is the source of truth.
// Regenerate if the site's service catalog changes. Do not hand-edit.
export type CatalogSeedEntry = {
  slug: string;          // full path slug, verbatim from services.ts
  name: string;          // the service h1, verbatim
  summary: string;       // the service metaDescription, verbatim
  categorySlug: string;  // first path segment of slug
  categoryLabel: string; // human label from nav.ts (fallback: title-cased categorySlug)
  category: 'WEB' | 'MOBILE' | 'SOFTWARE' | 'CLOUD' | 'AI' | 'DATA' | 'CONSULTING' | 'OTHER';
  deliverables: string[]; // the "What you get" / deliverables array, verbatim, order preserved
};

export const CATALOG_SEED: CatalogSeedEntry[] = [
  {
    slug: "software-engineering/custom-software-development",
    name: "Custom Software Development for Enterprise Operations",
    summary: "Innovatix Systems builds custom software for enterprise operations — from ERP and portals to AI automation — with a connected client portal for full project transparency.",
    categorySlug: "software-engineering",
    categoryLabel: "Software Engineering",
    category: "SOFTWARE",
    deliverables: [
      "Discovery, requirements, and a documented solution architecture",
      "A production application built on a connected data model",
      "Integrations with your marketplaces, payments, shipping, and finance systems",
      "Role-based access control, audit logging, and secure authentication",
      "Automated tests, CI/CD pipeline, and monitoring",
      "Documentation, handover, and ongoing support options",
    ],
  },
  {
    slug: "software-engineering/enterprise-software-development",
    name: "Enterprise Software Development",
    summary: "Innovatix Systems engineers enterprise software built to scale — multi-tenant architecture, SSO and RBAC, audit logging, deep integrations, and observability — with full delivery transparency.",
    categorySlug: "software-engineering",
    categoryLabel: "Software Engineering",
    category: "SOFTWARE",
    deliverables: [
      "Solution architecture, threat model, and a documented data model",
      "A multi-tenant platform with tenant isolation and RBAC",
      "Enterprise SSO, audit logging, and secure secrets management",
      "An API-first integration layer for cross-department systems",
      "CI/CD, automated tests, observability, and disaster-recovery plan",
      "Documentation, security review support, and a maintenance plan",
    ],
  },
  {
    slug: "ai-services/ai-automation",
    name: "AI Automation for Enterprise Operations",
    summary: "Innovatix Systems builds production AI automation — document intelligence, workflow automation, and grounded AI agents — with retrieval on your own data, human-in-the-loop review, and enterprise guardrails.",
    categorySlug: "ai-services",
    categoryLabel: "AI Services",
    category: "AI",
    deliverables: [
      "An automation opportunity assessment with prioritized ROI",
      "Grounded AI workflows integrated into your existing systems",
      "Document-intelligence pipelines (extract, classify, route)",
      "Human-in-the-loop review and approval controls",
      "Evaluations, guardrails, monitoring, and audit logging",
      "Documentation and a plan to expand automation safely",
    ],
  },
  {
    slug: "enterprise-systems/erp-development",
    name: "Custom ERP Development",
    summary: "Innovatix Systems builds custom ERP software around how your business actually operates — orders, inventory, purchasing, and finance in one connected system, integrated with your channels, carriers, and payments.",
    categorySlug: "enterprise-systems",
    categoryLabel: "Enterprise Systems",
    category: "SOFTWARE",
    deliverables: [
      "Order management with multi-channel support",
      "Inventory and warehouse management with real-time stock",
      "Purchasing and vendor management workflows",
      "Finance and accounts-receivable workflows",
      "Live operational dashboards and reporting",
      "Integrations (channels, carriers, payments, accounting), RBAC, and audit logging",
    ],
  },
  {
    slug: "software-engineering/api-development",
    name: "API Development for Enterprise Integration",
    summary: "Innovatix Systems designs and builds production APIs — REST and GraphQL, OAuth2/JWT auth, rate limiting, versioning, and OpenAPI docs — so your systems, partners, and AI agents integrate reliably.",
    categorySlug: "software-engineering",
    categoryLabel: "Software Engineering",
    category: "SOFTWARE",
    deliverables: [
      "OpenAPI 3.x specification (or GraphQL schema) as the reviewable, versioned contract",
      "Authentication and authorization layer — OAuth2 / JWT / scoped API keys with per-consumer permissions",
      "Rate limiting, quota, and throttling rules matched to each consumer tier",
      "Webhook or event-stream delivery for asynchronous integrations, with signing and retry/backoff",
      "Interactive API documentation and, where useful, generated client SDKs",
      "Request logging, tracing, and per-endpoint error/latency monitoring in production",
    ],
  },
  {
    slug: "software-engineering/systems-integration",
    name: "Systems Integration: One Source of Truth Across Every System You Run On",
    summary: "Custom systems integration that unifies ERP, marketplaces, payments, carriers, and accounting into one reliable source of truth — event-driven, idempotent, observable.",
    categorySlug: "software-engineering",
    categoryLabel: "Software Engineering",
    category: "SOFTWARE",
    deliverables: [
      "Integration architecture document mapping every system, data owner, and event flow before a line of code is written",
      "Event-driven integration layer (queues/webhooks) connecting ERP, marketplaces, payment processors, and carriers",
      "Data mapping and transformation layer reconciling field-level differences (SKUs, units, tax codes, statuses) between systems",
      "Idempotency, retry, and dead-letter handling so duplicate or failed deliveries never corrupt downstream data",
      "Monitoring and alerting dashboards for sync health, queue backlogs, and reconciliation drift",
      "Connected client portal giving your team full transparency into integration status, error logs, and data flow — no black box",
    ],
  },
  {
    slug: "ai-services/ai-agents",
    name: "AI Agents That Take Action Inside Your Systems",
    summary: "We build AI agents that take real action inside your ERP, CRM, and OMS — tool-calling, planning, guardrails, human approval, and full audit trails.",
    categorySlug: "ai-services",
    categoryLabel: "AI Services",
    category: "AI",
    deliverables: [
      "Agent capability map and permission scoping — exactly which actions the agent may take autonomously versus route for human approval",
      "Tool/function-calling integration layer connecting the agent to your ERP, CRM, OMS, or WMS through secured, scoped APIs",
      "Retrieval pipeline that grounds agent decisions in your own product, order, and policy data instead of general model knowledge",
      "Human-in-the-loop approval workflow with a review queue for high-risk, high-cost, or irreversible actions",
      "Evaluation, tracing, and observability stack covering run logs, failure rates, and per-agent cost so you can see what it is doing and what it costs",
      "Connected client portal for full transparency into agent activity, approvals pending, and outcomes over time",
    ],
  },
  {
    slug: "ai-services/document-intelligence",
    name: "Document Intelligence: From Unstructured Paperwork to Validated System Data",
    summary: "Turn invoices, POs, contracts, and forms into validated structured data automatically. OCR + LLM extraction, confidence scoring, human-in-the-loop review, and direct posting to your ERP or AP system.",
    categorySlug: "ai-services",
    categoryLabel: "AI Services",
    category: "AI",
    deliverables: [
      "Document classification model covering your specific document types (invoices, POs, packing slips, remittances, contracts, forms)",
      "OCR + LLM extraction pipeline with field- and line-item-level schema mapping per document type",
      "Confidence scoring engine with configurable thresholds for auto-post vs. human review",
      "Human-in-the-loop review interface for low-confidence or exception documents",
      "API integration posting validated data directly into your ERP, AP, OMS, or warehouse system",
      "Full audit trail and reporting on extraction accuracy, review volume, and processing throughput",
    ],
  },
  {
    slug: "enterprise-systems/crm-development",
    name: "CRM Development for Teams Outgrowing Off-the-Shelf Sales Tools",
    summary: "Custom CRM development that models your actual pipeline, quoting, and service workflows instead of forcing your team into HubSpot or Salesforce templates.",
    categorySlug: "enterprise-systems",
    categoryLabel: "Enterprise Systems",
    category: "SOFTWARE",
    deliverables: [
      "Custom pipeline and deal-stage engine with configurable approval gates and discount/margin rules",
      "Account, contact, and territory data model supporting parent/child hierarchies and multi-location accounts",
      "Quoting module with live pricing and inventory lookups against your ERP/OMS",
      "Activity and communication logging (email, calls, meetings, support notes) tied automatically to the correct account or deal",
      "Role-based permissions and territory assignment rules controlling record visibility and edit access",
      "Sales and pipeline reporting/dashboards built on your actual stage and forecast definitions, plus a data migration path from your existing CRM",
    ],
  },
  {
    slug: "enterprise-systems/warehouse-management-systems",
    name: "Custom Warehouse Management Systems Built Around Your Floor, Not a Vendor Template",
    summary: "Custom WMS software for receiving, putaway, directed picking, cycle counts, and multi-warehouse operations — built around how your floor actually runs, synced in real time with your ERP and OMS.",
    categorySlug: "enterprise-systems",
    categoryLabel: "Enterprise Systems",
    category: "SOFTWARE",
    deliverables: [
      "Receiving and putaway workflows with configurable, vendor- and product-specific rules",
      "Directed picking and packing (single-order, batch, and wave) tuned to your warehouse layout",
      "Bin, zone, and multi-location inventory model with full location and lot/serial traceability",
      "Mobile and handheld barcode scanning app for receiving, putaway, picking, packing, and cycle counts",
      "Real-time inventory sync with ERP, OMS, and storefront/marketplace channels",
      "Carrier and label integration for pack-and-ship, plus a connected client portal for full transparency into warehouse activity and integration status",
    ],
  },
  {
    slug: "enterprise-systems/inventory-management-systems",
    name: "Inventory Management Systems Built for Multi-Channel, Multi-Location Accuracy",
    summary: "Custom inventory management systems with real-time, multi-location stock accuracy — available-to-promise, reservations, replenishment, lot/serial tracking, and live sync to every sales channel.",
    categorySlug: "enterprise-systems",
    categoryLabel: "Enterprise Systems",
    category: "SOFTWARE",
    deliverables: [
      "Real-time available-to-promise engine spanning all warehouses, stores, and sales channels",
      "Reservation and allocation logic with configurable expiry, backorder, and pre-order handling",
      "Lot, serial, and expiry tracking for SKUs that require batch traceability or compliance",
      "FIFO or average-cost inventory valuation with landed cost support",
      "Replenishment and inter-location transfer recommendations driven by velocity and lead time",
      "Continuous sync connectors to marketplaces, storefront, OMS, WMS, and ERP to prevent overselling",
    ],
  },
  {
    slug: "enterprise-systems/order-management-systems",
    name: "Custom Order Management System Development",
    summary: "Custom order management systems that unify orders from marketplaces, storefronts, wholesale/EDI, and phone — with smart routing, split fulfillment, and exception handling.",
    categorySlug: "enterprise-systems",
    categoryLabel: "Enterprise Systems",
    category: "SOFTWARE",
    deliverables: [
      "Unified order capture and adapters for marketplace, storefront, wholesale/EDI (X12 850/855/856/810), and manual/phone order entry",
      "Payment authorization, capture, and refund orchestration integrated with your processor(s), including split-payment and net-terms handling",
      "Configurable inventory allocation and fulfillment routing engine supporting multi-warehouse, 3PL, and drop-ship vendor networks",
      "Split-shipment, backorder, and partial-fulfillment logic with customer-facing status that reflects reality per shipment",
      "Returns and RMA workflow with restock/dispose/vendor-return branching and accounting-side credit reconciliation",
      "Unified order status API and operations dashboard giving every internal system and support team one source of truth",
    ],
  },
  {
    slug: "cloud-infrastructure/cloud-architecture",
    name: "Cloud Architecture That Scales Without a Rewrite",
    summary: "AWS-based cloud architecture built for reliability, security, and cost control — networking, compute, IaC, autoscaling, HA/DR, and observability designed to grow without a rewrite.",
    categorySlug: "cloud-infrastructure",
    categoryLabel: "Cloud & Infrastructure",
    category: "CLOUD",
    deliverables: [
      "Well-Architected review and target-state architecture diagram",
      "VPC and networking design with private/public subnet segmentation and security groups",
      "Infrastructure-as-code repository (Terraform or AWS CDK) covering every environment",
      "CI/CD pipelines for both infrastructure changes and application deployments",
      "Autoscaling, high-availability, and disaster-recovery configuration with documented RTO/RPO",
      "Observability stack — metrics, logs, tracing, and alerting — plus a connected client portal for full transparency into infrastructure health and cost",
    ],
  },
  {
    slug: "data-analytics/data-engineering",
    name: "Data Engineering for a Single Source of Truth",
    summary: "Innovatix Systems builds the data engineering foundation your analytics run on — reliable pipelines, a modeled warehouse, and one trustworthy source of truth across every system.",
    categorySlug: "data-analytics",
    categoryLabel: "Data & Analytics",
    category: "DATA",
    deliverables: [
      "Source inventory and a target data model documented up front",
      "Ingestion pipelines with retries, idempotency, and failure alerting",
      "A modeled, tested warehouse (staging → core → marts)",
      "Data-quality tests: freshness, uniqueness, referential integrity",
      "Documentation and a data dictionary for self-service",
      "Monitoring, runbooks, and ongoing support options",
    ],
  },
  {
    slug: "data-analytics/data-warehousing",
    name: "Data Warehouse Development",
    summary: "Innovatix Systems designs and builds data warehouses that unify your systems into one governed, query-ready model — the foundation for reporting, BI, and AI.",
    categorySlug: "data-analytics",
    categoryLabel: "Data & Analytics",
    category: "DATA",
    deliverables: [
      "A dimensional data model (facts, conformed dimensions) documented",
      "A provisioned, governed warehouse with role-based access",
      "Scheduled, monitored loads with history capture",
      "Conformed metric definitions and a data dictionary",
      "Query performance tuning and cost controls",
      "Documentation, handover, and support options",
    ],
  },
  {
    slug: "data-analytics/etl-pipelines",
    name: "ETL & Data Pipeline Development",
    summary: "Innovatix Systems builds ETL and data pipelines that move data between your systems reliably — with retries, idempotency, and alerting so nothing silently breaks.",
    categorySlug: "data-analytics",
    categoryLabel: "Data & Analytics",
    category: "DATA",
    deliverables: [
      "Source-to-target mapping and pipeline design",
      "Idempotent, retried, ordered pipelines (batch and/or streaming)",
      "Freshness, run-status, and reconciliation monitoring with alerts",
      "Backfill and replay tooling for corrections",
      "Logging, runbooks, and on-call-ready documentation",
      "Handover and ongoing support options",
    ],
  },
  {
    slug: "data-analytics/business-intelligence",
    name: "Business Intelligence That Teams Actually Use",
    summary: "Innovatix Systems turns your data into decision-ready business intelligence — governed metrics, reports, and self-service dashboards built on a trustworthy foundation.",
    categorySlug: "data-analytics",
    categoryLabel: "Data & Analytics",
    category: "DATA",
    deliverables: [
      "A governed, documented metrics layer with conformed definitions",
      "Executive and operational dashboards designed around decisions",
      "Curated self-service datasets with role-based access",
      "Data freshness and reconciliation against systems of record",
      "Training and documentation for report consumers",
      "Ongoing enhancement and support options",
    ],
  },
  {
    slug: "data-analytics/executive-dashboards",
    name: "Executive Dashboards for Real Decisions",
    summary: "Innovatix Systems builds executive dashboards that give leadership one live, trustworthy view of the business — the KPIs that matter, updated automatically, reconciled to source.",
    categorySlug: "data-analytics",
    categoryLabel: "Data & Analytics",
    category: "DATA",
    deliverables: [
      "A KPI definition workshop with leadership",
      "A focused executive dashboard with the vital-few metrics",
      "Automated refresh from a governed warehouse",
      "Drill-downs from each KPI to its drivers",
      "Reconciliation with finance and operational systems",
      "Access controls, training, and support options",
    ],
  },
  {
    slug: "data-analytics/predictive-analytics",
    name: "Predictive Analytics, Grounded in Your Data",
    summary: "Innovatix Systems builds predictive analytics grounded in your operational data — demand forecasting, churn and risk scoring, and models wired into the workflows that use them.",
    categorySlug: "data-analytics",
    categoryLabel: "Data & Analytics",
    category: "DATA",
    deliverables: [
      "A use-case and feasibility assessment tied to a real decision",
      "A predictive model trained on your governed data",
      "Delivery of predictions into the workflow (UI, flag, or API)",
      "Confidence signals and a defined fallback behavior",
      "Drift monitoring and a retraining plan",
      "Documentation, handover, and support options",
    ],
  },
  {
    slug: "software-engineering/saas-product-development",
    name: "SaaS Product Development, Engineered to Scale",
    summary: "Innovatix Systems builds SaaS products end to end — multi-tenant architecture, subscription billing, secure auth, and the delivery transparency to ship and iterate with confidence.",
    categorySlug: "software-engineering",
    categoryLabel: "Software Engineering",
    category: "SOFTWARE",
    deliverables: [
      "Multi-tenant architecture with enforced tenant isolation",
      "Subscription billing (plans, trials, proration, webhooks)",
      "Authentication, roles, permissions, and team management",
      "Self-service onboarding and account administration",
      "Usage metering and admin/reporting surfaces",
      "CI/CD, monitoring, and documentation",
    ],
  },
  {
    slug: "software-engineering/web-application-development",
    name: "Custom Web Application Development",
    summary: "Innovatix Systems builds custom web applications — dashboards, portals, and operational tools — that are fast, secure, and engineered around your workflows, not a template.",
    categorySlug: "software-engineering",
    categoryLabel: "Software Engineering",
    category: "WEB",
    deliverables: [
      "A custom web application built on a modeled data layer",
      "Role-based access control and secure authentication",
      "Responsive UI designed around your real workflows",
      "Integrations with the systems the app depends on",
      "Automated tests, CI/CD, and monitoring",
      "Documentation, handover, and support options",
    ],
  },
  {
    slug: "software-engineering/mobile-application-development",
    name: "Mobile Applications for the Way You Operate",
    summary: "Innovatix Systems builds mobile applications for operations — field reps, warehouse scanning, and customer apps — connected to the same systems your business runs on.",
    categorySlug: "software-engineering",
    categoryLabel: "Software Engineering",
    category: "MOBILE",
    deliverables: [
      "A mobile app (PWA or cross-platform/native) for your use case",
      "Barcode/QR scanning and device-camera workflows where needed",
      "Real-time connection to your operational backend",
      "Offline-tolerant capture with sync where required",
      "Role-based access and secure authentication",
      "Store submission support (native), documentation, and support",
    ],
  },
  {
    slug: "software-engineering/legacy-modernization",
    name: "Legacy Software Modernization",
    summary: "Innovatix Systems modernizes legacy software safely — data migration, incremental replacement, and a rollback plan at every step, so operations never stop.",
    categorySlug: "software-engineering",
    categoryLabel: "Software Engineering",
    category: "SOFTWARE",
    deliverables: [
      "An assessment of the current system, data, and integrations",
      "A phased modernization plan with reversible increments",
      "Incremental replacement behind a stable interface",
      "Verified data migration with reconciliation",
      "Automated tests, CI/CD, and monitoring on the new system",
      "Cutover, rollback plan, and post-migration support",
    ],
  },
  {
    slug: "software-engineering/maintenance-support",
    name: "Software Maintenance & Support",
    summary: "Innovatix Systems provides software maintenance and support — monitoring, security updates, bug fixes, and enhancements — so the systems your business depends on stay reliable.",
    categorySlug: "software-engineering",
    categoryLabel: "Software Engineering",
    category: "SOFTWARE",
    deliverables: [
      "Monitoring, alerting, and incident response",
      "Security patches and dependency updates",
      "Bug fixes and reliability improvements",
      "Verified backups and recovery readiness",
      "Scoped enhancements and change requests",
      "Regular reporting on health, work done, and risks",
    ],
  },
  {
    slug: "security/secure-architecture",
    name: "Secure Software Architecture",
    summary: "Innovatix Systems designs secure software architecture from the first commit — tenant isolation, least privilege, and defense in depth built in, not bolted on.",
    categorySlug: "security",
    categoryLabel: "Security",
    category: "SOFTWARE",
    deliverables: [
      "A threat-informed architecture and data-isolation design",
      "Least-privilege access model for users and services",
      "Encryption in transit and at rest, and secrets management",
      "Dependency scanning and supply-chain hygiene",
      "Security tests (including cross-tenant isolation)",
      "Architecture documentation and a hardening checklist",
    ],
  },
  {
    slug: "security/authentication-authorization",
    name: "Authentication & Authorization",
    summary: "Innovatix Systems builds authentication and authorization the right way — secure sessions, strong password handling, MFA-ready flows, and server-authoritative permissions.",
    categorySlug: "security",
    categoryLabel: "Security",
    category: "SOFTWARE",
    deliverables: [
      "Authentication with secure sessions and strong credential storage",
      "MFA-ready flows and account lifecycle (invite, deactivate)",
      "Server-authoritative authorization / permission checks",
      "Separate trust domains for staff vs. customer identities",
      "Audit trail for sensitive auth events",
      "Documentation and security tests",
    ],
  },
  {
    slug: "security/sso-enterprise-identity",
    name: "SSO & Enterprise Identity Integration",
    summary: "Innovatix Systems integrates single sign-on and enterprise identity — SAML/OIDC with Okta, Azure AD, and Google Workspace — with provisioning and central access control.",
    categorySlug: "security",
    categoryLabel: "Security",
    category: "SOFTWARE",
    deliverables: [
      "SAML/OIDC integration with your identity provider",
      "Role/group claim mapping to application permissions",
      "Just-in-time or SCIM-style provisioning where supported",
      "Central revocation and offboarding flow",
      "Fallback and break-glass access handling",
      "Documentation and configuration handover",
    ],
  },
  {
    slug: "security/rbac",
    name: "Role-Based Access Control (RBAC)",
    summary: "Innovatix Systems designs and builds role-based access control — clear roles and permissions, server-enforced, auditable, and flexible enough for real organizations.",
    categorySlug: "security",
    categoryLabel: "Security",
    category: "SOFTWARE",
    deliverables: [
      "A documented role/permission matrix",
      "Server-side permission enforcement across the app",
      "Organization/tenant scoping of access",
      "Self-lockout and last-owner protections",
      "Audit events for permission-sensitive actions",
      "Tests proving each role’s boundaries",
    ],
  },
  {
    slug: "security/audit-logging",
    name: "Audit Logging",
    summary: "Innovatix Systems builds audit logging that makes sensitive actions traceable — who did what, when, and to what — the foundation of accountability and compliance readiness.",
    categorySlug: "security",
    categoryLabel: "Security",
    category: "SOFTWARE",
    deliverables: [
      "An audit event model (actor, action, target, tenant, time)",
      "Consistent capture of sensitive actions through one path",
      "Correct actor attribution and tenant scoping",
      "Durable storage and retention policy",
      "Review/query access to the audit trail",
      "Documentation mapping actions to audit coverage",
    ],
  },
  {
    slug: "security/application-security",
    name: "Application Security",
    summary: "Innovatix Systems hardens applications against real-world attacks — input validation, safe file handling and malware scanning, dependency hygiene, and secure defaults.",
    categorySlug: "security",
    categoryLabel: "Security",
    category: "SOFTWARE",
    deliverables: [
      "Input validation and injection/XSS mitigations",
      "Safe upload handling with malware scanning",
      "Dependency scanning and update process",
      "Secrets management and secure configuration",
      "Security-focused code review and remediation",
      "A hardening checklist and documentation",
    ],
  },
  {
    slug: "security/compliance-readiness",
    name: "Compliance-Readiness Engineering",
    summary: "Innovatix Systems engineers the technical controls that make audits and enterprise reviews pass — access control, audit logging, encryption, and evidence — without slowing you down.",
    categorySlug: "security",
    categoryLabel: "Security",
    category: "SOFTWARE",
    deliverables: [
      "A controls gap assessment against your target framework",
      "Least-privilege access and RBAC enforcement",
      "Audit logging and access/change evidence",
      "Encryption in transit and at rest, secrets management",
      "Secure change management (CI/CD, reviews, backups)",
      "Documentation and audit-evidence runbooks",
    ],
  },
  {
    slug: "digital-transformation/legacy-modernization",
    name: "Legacy System Modernization as a Program",
    summary: "Innovatix Systems runs legacy modernization as a program — assess the portfolio, sequence by business value and risk, and modernize system by system without stopping operations.",
    categorySlug: "digital-transformation",
    categoryLabel: "Digital Transformation",
    category: "CONSULTING",
    deliverables: [
      "A modernization assessment of the application estate",
      "A value- and risk-sequenced modernization roadmap",
      "A per-system incremental migration approach",
      "Data-migration strategy across the portfolio",
      "Governance, milestones, and executive reporting",
      "Execution of the modernization work, system by system",
    ],
  },
  {
    slug: "digital-transformation/process-automation",
    name: "Business Process Automation",
    summary: "Innovatix Systems automates the repetitive operational work draining your team — approvals, data entry, reconciliation, and handoffs — with custom workflows wired into your systems.",
    categorySlug: "digital-transformation",
    categoryLabel: "Digital Transformation",
    category: "CONSULTING",
    deliverables: [
      "A process map of the target workflow and its exceptions",
      "Automated workflows for the repetitive steps",
      "Integrations with the systems the process touches",
      "Approvals, routing, reminders, and notifications",
      "Exception handling with human-in-the-loop review",
      "Reporting on throughput, time saved, and exceptions",
    ],
  },
  {
    slug: "digital-transformation/systems-integration",
    name: "Operational Systems Integration",
    summary: "Innovatix Systems connects the operational systems your business runs on — ERP, marketplaces, carriers, payments, and finance — so data flows automatically instead of being re-keyed.",
    categorySlug: "digital-transformation",
    categoryLabel: "Digital Transformation",
    category: "CONSULTING",
    deliverables: [
      "An integration map of your systems and data flows",
      "Tested integrations with retries, idempotency, and monitoring",
      "A canonical data model where it reduces complexity",
      "Error handling, alerting, and reconciliation",
      "Documentation and runbooks",
      "Handover and ongoing support options",
    ],
  },
  {
    slug: "digital-transformation/digital-strategy",
    name: "Digital Strategy That Ships",
    summary: "Innovatix Systems builds pragmatic digital strategy grounded in engineering reality — tied to business outcomes, sequenced by value, and something we can actually deliver.",
    categorySlug: "digital-transformation",
    categoryLabel: "Digital Transformation",
    category: "CONSULTING",
    deliverables: [
      "A current-state assessment of systems and capabilities",
      "Target outcomes and the capabilities required",
      "A sequenced, value-based transformation roadmap",
      "Success metrics for each initiative",
      "Build-vs-buy and technology recommendations",
      "An executive-ready strategy document",
    ],
  },
  {
    slug: "digital-transformation/technology-roadmaps",
    name: "Technology Roadmaps",
    summary: "Innovatix Systems builds technology roadmaps that turn strategy into a sequenced, realistic plan — what to build, in what order, with the dependencies and risks made explicit.",
    categorySlug: "digital-transformation",
    categoryLabel: "Digital Transformation",
    category: "CONSULTING",
    deliverables: [
      "An inventory of initiatives with effort and risk",
      "An explicit dependency map",
      "A sequenced, phased roadmap with milestones",
      "Value and risk rationale for the ordering",
      "Assumptions, trade-offs, and decision points",
      "An executive-ready roadmap artifact",
    ],
  },
  {
    slug: "digital-transformation/architecture-assessments",
    name: "Software Architecture Assessment",
    summary: "Innovatix Systems assesses your software architecture — scalability, security, and maintainability — and delivers a prioritized, honest picture of the real risks and fixes.",
    categorySlug: "digital-transformation",
    categoryLabel: "Digital Transformation",
    category: "CONSULTING",
    deliverables: [
      "An architecture review across scalability, security, and maintainability",
      "A prioritized findings register (risk × impact)",
      "Remediation recommendations with rough effort",
      "A scaling and risk outlook",
      "A go/no-go or build/rebuild recommendation where relevant",
      "An executive summary plus technical detail",
    ],
  },
  {
    slug: "team-services/dedicated-teams",
    name: "Dedicated Development Teams",
    summary: "Innovatix Systems provides dedicated development teams that own delivery end to end — engineers, architecture, and process — working transparently through a connected client portal.",
    categorySlug: "team-services",
    categoryLabel: "Team Services",
    category: "CONSULTING",
    deliverables: [
      "A dedicated team matched to your work and stack",
      "Ownership of architecture, quality, and delivery",
      "Continuous delivery to your roadmap and priorities",
      "A connected portal with verified progress reporting",
      "Milestone approvals and change-request handling",
      "Ability to scale the team up or down as needs change",
    ],
  },
  {
    slug: "team-services/staff-augmentation",
    name: "Staff Augmentation",
    summary: "Innovatix Systems provides staff augmentation — senior engineers who slot into your team, work to your process, and add real capacity without long hiring cycles.",
    categorySlug: "team-services",
    categoryLabel: "Team Services",
    category: "CONSULTING",
    deliverables: [
      "Senior engineer(s) matched to your stack and needs",
      "Integration into your team, tools, and process",
      "Contribution under your direction and priorities",
      "Clear communication and collaboration",
      "Flexible ramp-up and wind-down",
      "Continuity and knowledge sharing with your team",
    ],
  },
  {
    slug: "team-services/technical-consulting",
    name: "Technical Consulting",
    summary: "Innovatix Systems provides technical consulting — senior, hands-on guidance on architecture, technology choices, and hard engineering decisions, grounded in real delivery.",
    categorySlug: "team-services",
    categoryLabel: "Team Services",
    category: "CONSULTING",
    deliverables: [
      "Senior guidance on the specific decision or problem",
      "Architecture and technology recommendations with rationale",
      "Trade-off analysis and risk assessment",
      "A clear, actionable recommendation",
      "Optional follow-up and advisory",
      "Written summary of decisions and reasoning",
    ],
  },
  {
    slug: "team-services/fractional-cto",
    name: "Fractional CTO",
    summary: "Innovatix Systems provides fractional CTO leadership — technology strategy, architecture, hiring, and delivery oversight — for companies that need senior direction without a full-time hire.",
    categorySlug: "team-services",
    categoryLabel: "Team Services",
    category: "CONSULTING",
    deliverables: [
      "Technology strategy and architecture direction",
      "Delivery oversight and engineering standards",
      "Hiring and team-development guidance",
      "Vendor and build-vs-buy decisions",
      "Risk, security, and roadmap ownership",
      "Regular leadership reporting to the business",
    ],
  },
  {
    slug: "team-services/architecture-reviews",
    name: "Architecture Reviews",
    summary: "Innovatix Systems provides architecture reviews — a senior second opinion on your design before you build — catching scalability, security, and maintainability issues early.",
    categorySlug: "team-services",
    categoryLabel: "Team Services",
    category: "CONSULTING",
    deliverables: [
      "A senior review of the proposed or current architecture",
      "Specific findings across scalability, security, and maintainability",
      "Prioritized, actionable recommendations",
      "Risks to watch as the system grows",
      "A concise written summary",
      "Optional follow-up as the design evolves",
    ],
  },
  {
    slug: "team-services/codebase-audits",
    name: "Codebase Audits",
    summary: "Innovatix Systems audits codebases for quality, security, and risk — an honest, prioritized picture of technical debt and what to fix, whether you own the code or are acquiring it.",
    categorySlug: "team-services",
    categoryLabel: "Team Services",
    category: "CONSULTING",
    deliverables: [
      "A review of code quality, architecture, and structure",
      "A security review of the implementation",
      "Test-coverage and dependency-health assessment",
      "A prioritized findings register (risk × impact)",
      "Remediation recommendations with rough effort",
      "An executive summary plus technical detail",
    ],
  },
  {
    slug: "ai-services/ai-strategy-consulting",
    name: "AI Strategy & Consulting",
    summary: "Innovatix Systems provides honest AI strategy and consulting — finding where AI genuinely creates value in your operations, and where it does not, grounded in what we can build.",
    categorySlug: "ai-services",
    categoryLabel: "AI Services",
    category: "AI",
    deliverables: [
      "An AI opportunity assessment across your operations",
      "Prioritized use cases ranked by value and feasibility",
      "Data and integration requirements per use case",
      "A guardrails approach (grounding, confidence, review)",
      "A realistic, sequenced AI roadmap",
      "A build-vs-buy recommendation per use case",
    ],
  },
  {
    slug: "ai-services/generative-ai",
    name: "Generative AI Application Development",
    summary: "Innovatix Systems builds generative AI applications that do real work — drafting, summarizing, and generating from your data — grounded, safe, and wired into your workflows.",
    categorySlug: "ai-services",
    categoryLabel: "AI Services",
    category: "AI",
    deliverables: [
      "A production generative-AI feature grounded in your data",
      "Retrieval/grounding so output cites real sources",
      "Guardrails: validation, confidence, and human review",
      "Integration into your existing workflow and tools",
      "Prompt and evaluation setup for quality",
      "Monitoring and iteration support",
    ],
  },
  {
    slug: "ai-services/rag",
    name: "Retrieval-Augmented Generation (RAG)",
    summary: "Innovatix Systems builds retrieval-augmented generation (RAG) systems that let AI answer from your own documents and data — accurately, with sources, and access-controlled.",
    categorySlug: "ai-services",
    categoryLabel: "AI Services",
    category: "AI",
    deliverables: [
      "Ingestion and chunking of your documents/data",
      "Tuned retrieval (search) returning relevant context",
      "Grounded generation with citations and \"I don’t know\"",
      "Access control on retrieved content",
      "An evaluation harness for answer quality",
      "Integration into your app or workflow",
    ],
  },
  {
    slug: "ai-services/chatbots-assistants",
    name: "AI Chatbots & Assistants",
    summary: "Innovatix Systems builds AI chatbots and assistants grounded in your knowledge — answering accurately, escalating to humans cleanly, and integrated with your systems.",
    categorySlug: "ai-services",
    categoryLabel: "AI Services",
    category: "AI",
    deliverables: [
      "A chatbot/assistant grounded in your knowledge (RAG)",
      "Human-handoff flow with full context transfer",
      "Integration to look up and act in your systems",
      "Guardrails, confidence, and safe fallbacks",
      "Channel integration (web, portal, or messaging)",
      "Analytics on resolution and escalation",
    ],
  },
  {
    slug: "ai-services/workflow-automation",
    name: "Intelligent Workflow Automation",
    summary: "Innovatix Systems builds intelligent workflow automation — AI handling the judgment steps (classify, extract, decide) inside your operational workflows, with humans on exceptions.",
    categorySlug: "ai-services",
    categoryLabel: "AI Services",
    category: "AI",
    deliverables: [
      "An automated workflow with AI on the judgment steps",
      "Confidence thresholds and human-in-the-loop exceptions",
      "Document/text understanding where needed",
      "Integration with the systems the workflow touches",
      "Monitoring, audit trail, and quality measurement",
      "Iteration as accuracy improves",
    ],
  },
  {
    slug: "ai-services/ai-integration",
    name: "AI Integration",
    summary: "Innovatix Systems integrates AI into the software you already run — adding grounded, guarded AI capabilities to your app, portal, or operations without a rebuild.",
    categorySlug: "ai-services",
    categoryLabel: "AI Services",
    category: "AI",
    deliverables: [
      "AI capabilities integrated into your existing software",
      "Grounding/retrieval and access control",
      "Guardrails: validation, confidence, and fallbacks",
      "A provider abstraction to avoid lock-in",
      "Monitoring and cost controls",
      "Documentation and iteration support",
    ],
  },
  {
    slug: "enterprise-systems/customer-portals",
    name: "Customer Portal Development",
    summary: "Innovatix Systems builds customer portals connected to your live operational data — orders, invoices, documents, and support — so customers self-serve and your team is freed up.",
    categorySlug: "enterprise-systems",
    categoryLabel: "Enterprise Systems",
    category: "SOFTWARE",
    deliverables: [
      "A branded customer portal on live operational data",
      "Self-service for orders, invoices, documents, and status",
      "Secure authentication and per-customer data scoping",
      "Support/messaging or ticket entry point",
      "Notifications for updates that matter",
      "Integrations, audit logging, and support options",
    ],
  },
  {
    slug: "enterprise-systems/vendor-portals",
    name: "Vendor & Supplier Portal Development",
    summary: "Innovatix Systems builds vendor and supplier portals — POs, ASNs, invoices, and documents in one connected place — so procurement runs on data instead of email and spreadsheets.",
    categorySlug: "enterprise-systems",
    categoryLabel: "Enterprise Systems",
    category: "SOFTWARE",
    deliverables: [
      "A supplier portal for POs, confirmations, ASNs, and invoices",
      "PO/invoice/receipt matching to reduce disputes",
      "Document exchange and shared status",
      "Secure, per-vendor access and audit logging",
      "Integration with your ERP/procurement systems",
      "Notifications and support options",
    ],
  },
  {
    slug: "enterprise-systems/finance-ar-systems",
    name: "Finance & Accounts Receivable Systems",
    summary: "Innovatix Systems builds finance and AR systems tied to your orders — invoicing, receivables, payments, and reconciliation — so billing and cash flow stay accurate and in sync.",
    categorySlug: "enterprise-systems",
    categoryLabel: "Enterprise Systems",
    category: "SOFTWARE",
    deliverables: [
      "Order-tied invoicing and billing",
      "Accounts-receivable and aging tracking",
      "Payment capture and reconciliation",
      "Net-terms/credit handling where needed",
      "Finance reporting and audit trail",
      "Integration with accounting and your operations",
    ],
  },
  {
    slug: "enterprise-systems/business-operations-platforms",
    name: "Business Operations Platforms",
    summary: "Innovatix Systems builds the operations platform your business runs on — orders, inventory, fulfillment, finance, and portals unified on one connected source of truth.",
    categorySlug: "enterprise-systems",
    categoryLabel: "Enterprise Systems",
    category: "SOFTWARE",
    deliverables: [
      "A connected operations platform on one data model",
      "Order, inventory, and fulfillment modules",
      "Finance/AR tied to operations",
      "Customer and vendor portals",
      "Marketplace, carrier, and payment integrations",
      "RBAC, audit logging, reporting, and support",
    ],
  },
  {
    slug: "cloud-infrastructure/cloud-migration",
    name: "Cloud Migration",
    summary: "Innovatix Systems migrates applications and data to the cloud safely — assessed, sequenced, and reversible — so you gain scalability and reliability without downtime surprises.",
    categorySlug: "cloud-infrastructure",
    categoryLabel: "Cloud & Infrastructure",
    category: "CLOUD",
    deliverables: [
      "A migration assessment and per-workload strategy",
      "A sequenced migration and cutover plan with rollback",
      "Data migration with validation and reconciliation",
      "Right-sized cloud architecture and cost controls",
      "Monitoring, backups, and DR readiness",
      "Documentation and post-migration support",
    ],
  },
  {
    slug: "cloud-infrastructure/aws-engineering",
    name: "AWS Engineering",
    summary: "Innovatix Systems designs and operates AWS infrastructure the right way — secure, scalable, and cost-aware — with the compute, data, and networking your workloads actually need.",
    categorySlug: "cloud-infrastructure",
    categoryLabel: "Cloud & Infrastructure",
    category: "CLOUD",
    deliverables: [
      "A well-architected AWS design for your workloads",
      "Compute, data, and networking set up securely",
      "Least-privilege IAM and encryption",
      "Infrastructure as code and repeatable environments",
      "Cost monitoring, right-sizing, and controls",
      "Monitoring, backups, and operational runbooks",
    ],
  },
  {
    slug: "cloud-infrastructure/azure-engineering",
    name: "Azure Engineering",
    summary: "Innovatix Systems engineers Microsoft Azure infrastructure — secure, scalable, and integrated with Entra ID — for organizations standardized on the Microsoft ecosystem.",
    categorySlug: "cloud-infrastructure",
    categoryLabel: "Cloud & Infrastructure",
    category: "CLOUD",
    deliverables: [
      "A well-architected Azure design for your workloads",
      "Compute, data, and networking configured securely",
      "Entra ID (Azure AD) identity integration",
      "Infrastructure as code and governance/policy",
      "Cost monitoring and controls",
      "Monitoring, backups, and runbooks",
    ],
  },
  {
    slug: "cloud-infrastructure/devops",
    name: "DevOps",
    summary: "Innovatix Systems brings DevOps practices to your team — automated pipelines, infrastructure as code, and monitoring — so you ship more often with less risk.",
    categorySlug: "cloud-infrastructure",
    categoryLabel: "Cloud & Infrastructure",
    category: "CLOUD",
    deliverables: [
      "CI/CD pipelines for build, test, and deploy",
      "Infrastructure as code and consistent environments",
      "Automated testing gates in the pipeline",
      "Monitoring, alerting, and health checks",
      "Rollback and safe-deploy practices",
      "Documentation and team enablement",
    ],
  },
  {
    slug: "cloud-infrastructure/ci-cd",
    name: "CI/CD Pipeline Setup",
    summary: "Innovatix Systems builds CI/CD pipelines that test and deploy every change automatically — with quality gates, safe rollouts, and rollback — so shipping is routine and reliable.",
    categorySlug: "cloud-infrastructure",
    categoryLabel: "Cloud & Infrastructure",
    category: "CLOUD",
    deliverables: [
      "CI/CD pipeline for build, test, and deploy",
      "Automated test and quality gates",
      "Environment promotion (dev → staging → prod)",
      "Safe rollout strategy and fast rollback",
      "Secrets handling in the pipeline",
      "Documentation and team handover",
    ],
  },
  {
    slug: "cloud-infrastructure/infrastructure-as-code",
    name: "Infrastructure as Code",
    summary: "Innovatix Systems defines your infrastructure as code — reproducible, reviewable, version-controlled environments with Terraform/CDK — so nothing is a fragile hand-built snowflake.",
    categorySlug: "cloud-infrastructure",
    categoryLabel: "Cloud & Infrastructure",
    category: "CLOUD",
    deliverables: [
      "Your infrastructure defined as version-controlled code",
      "Consistent dev/staging/prod environments",
      "Plan/preview and review workflow for changes",
      "State management and secrets handling",
      "Documentation and modules for reuse",
      "Recovery/rebuild capability",
    ],
  },
  {
    slug: "cloud-infrastructure/kubernetes",
    name: "Kubernetes Engineering",
    summary: "Innovatix Systems designs and operates Kubernetes — when it is the right tool — with secure, scalable, observable clusters, and the honesty to say when you do not need it.",
    categorySlug: "cloud-infrastructure",
    categoryLabel: "Cloud & Infrastructure",
    category: "CLOUD",
    deliverables: [
      "A fit assessment (do you need Kubernetes?)",
      "A secure, right-sized cluster design",
      "Deployments, autoscaling, and resource limits",
      "Network policy, RBAC, and secrets handling",
      "Observability (metrics, logs, alerts)",
      "Infrastructure as code and operational runbooks",
    ],
  },
  {
    slug: "cloud-infrastructure/monitoring-observability",
    name: "Monitoring & Observability",
    summary: "Innovatix Systems builds monitoring and observability — metrics, logs, health checks, and actionable alerts — so you find and fix problems before customers ever notice.",
    categorySlug: "cloud-infrastructure",
    categoryLabel: "Cloud & Infrastructure",
    category: "CLOUD",
    deliverables: [
      "Metrics and dashboards for app and infrastructure",
      "Structured, correlated logging",
      "Health/readiness checks",
      "Actionable alerting on meaningful conditions",
      "On-call/runbook setup",
      "Documentation and tuning",
    ],
  },
];
