// Zero-dependency invoice PDF renderer.
//
// This is the *stub* PDF provider: it hand-assembles a minimal but fully valid
// single-page PDF (Helvetica text) so the billing loop works end-to-end in dev
// without pulling a heavyweight renderer. In production a real provider
// (headless-Chrome / a templating service) would replace `renderInvoicePdf`
// behind the same signature — see billing/index.ts.

type Line = { description: string; quantity: number; unitCents: number; amountCents: number; milestoneName?: string | null };
type InvoicePdfInput = {
  number: string;
  currency: string;
  status: string;
  amountCents: number;
  issuedAt: Date | string | null;
  dueAt: Date | string | null;
  paidAt: Date | string | null;
  billingContactName: string | null;
  orgName: string;
  lineItems: Line[];
};

const money = (cents: number, currency: string) =>
  new Intl.NumberFormat('en-US', { style: 'currency', currency: currency || 'USD' }).format(cents / 100);
const day = (d: Date | string | null) =>
  d ? new Date(d).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' }) : '—';

// PDF strings must escape \ ( ) and drop non-Latin control chars.
const esc = (s: string) => String(s).replace(/[\\()]/g, (c) => `\\${c}`).replace(/[\r\n\t]/g, ' ').replace(/[^\x20-\x7E]/g, '');
const clip = (s: string, n: number) => (s.length > n ? `${s.slice(0, n - 1)}…`.replace('…', '...') : s);

/** Build a text run positioned at (x, y) from the page bottom-left, size pt. */
function text(x: number, y: number, size: number, s: string, bold = false) {
  return `BT /${bold ? 'F2' : 'F1'} ${size} Tf ${x} ${y} Td (${esc(s)}) Tj ET\n`;
}

export function renderInvoicePdf(inv: InvoicePdfInput): Buffer {
  const W = 612; // US Letter
  let y = 760;
  let body = '';

  body += text(50, y, 20, 'Innovatix Systems', true); y -= 14;
  body += text(50, y, 9, 'Software development & delivery'); y -= 30;

  body += text(50, y, 15, `Invoice ${inv.number}`, true);
  body += text(400, y, 12, money(inv.amountCents, inv.currency), true); y -= 18;
  body += text(50, y, 9, `Status: ${inv.status}`);
  body += text(50, y - 12, 9, `Billed to: ${inv.orgName}${inv.billingContactName ? ` (${inv.billingContactName})` : ''}`);
  body += text(400, y, 9, `Issued: ${day(inv.issuedAt)}`);
  body += text(400, y - 12, 9, inv.status === 'PAID' ? `Paid: ${day(inv.paidAt)}` : `Due: ${day(inv.dueAt)}`);
  y -= 40;

  // Column headers
  body += text(50, y, 9, 'DESCRIPTION', true);
  body += text(360, y, 9, 'QTY', true);
  body += text(410, y, 9, 'UNIT', true);
  body += text(500, y, 9, 'AMOUNT', true);
  y -= 4;
  body += `50 ${y} m 562 ${y} l S\n`; // rule
  y -= 16;

  for (const li of inv.lineItems) {
    const desc = clip(li.description + (li.milestoneName ? ` [${li.milestoneName}]` : ''), 60);
    body += text(50, y, 10, desc);
    body += text(360, y, 10, String(li.quantity));
    body += text(410, y, 10, money(li.unitCents, inv.currency));
    body += text(500, y, 10, money(li.amountCents, inv.currency));
    y -= 18;
    if (y < 90) break; // single page guard
  }

  y -= 6;
  body += `360 ${y} m 562 ${y} l S\n`; y -= 18;
  body += text(410, y, 12, 'Total', true);
  body += text(500, y, 12, money(inv.amountCents, inv.currency), true);

  body += text(50, 50, 8, 'Thank you for your business.  Generated by Innovatix Systems.');

  // Line-drawing needs a stroke width; prepend graphics state.
  const content = `1 w\n${body}`;

  // Assemble objects with a correct xref table.
  const objs: string[] = [];
  objs[1] = '<< /Type /Catalog /Pages 2 0 R >>';
  objs[2] = '<< /Type /Pages /Kids [3 0 R] /Count 1 >>';
  objs[3] = `<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${W} 792] /Contents 4 0 R /Resources << /Font << /F1 5 0 R /F2 6 0 R >> >> >>`;
  objs[4] = `<< /Length ${Buffer.byteLength(content)} >>\nstream\n${content}\nendstream`;
  objs[5] = '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>';
  objs[6] = '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>';

  let pdf = '%PDF-1.4\n';
  const offsets: number[] = [];
  for (let i = 1; i < objs.length; i++) {
    offsets[i] = Buffer.byteLength(pdf);
    pdf += `${i} 0 obj\n${objs[i]}\nendobj\n`;
  }
  const xrefPos = Buffer.byteLength(pdf);
  const count = objs.length; // includes index 0
  pdf += `xref\n0 ${count}\n0000000000 65535 f \n`;
  for (let i = 1; i < objs.length; i++) {
    pdf += `${String(offsets[i]).padStart(10, '0')} 00000 n \n`;
  }
  pdf += `trailer\n<< /Size ${count} /Root 1 0 R >>\nstartxref\n${xrefPos}\n%%EOF`;
  return Buffer.from(pdf, 'latin1');
}

// Map an enriched invoice (from lib/invoices enrichInvoice) + org name into the
// renderer input, picking only the fields the PDF needs.
type EnrichedForPdf = {
  number: string; currency: string; status: string; amountCents: number;
  issuedAt: Date | string | null; dueAt: Date | string | null; paidAt: Date | string | null;
  billingContactName: string | null;
  lineItems: { description: string; quantity: number; unitCents: number; amountCents: number; milestoneName?: string | null }[];
};
export function renderInvoicePdfFrom(inv: EnrichedForPdf, orgName: string): Buffer {
  return renderInvoicePdf({
    number: inv.number, currency: inv.currency, status: inv.status, amountCents: inv.amountCents,
    issuedAt: inv.issuedAt, dueAt: inv.dueAt, paidAt: inv.paidAt,
    billingContactName: inv.billingContactName, orgName,
    lineItems: inv.lineItems.map((li) => ({ description: li.description, quantity: li.quantity, unitCents: li.unitCents, amountCents: li.amountCents, milestoneName: li.milestoneName ?? null })),
  });
}
